---
- name:
  vars_files:
  - ../vars.yml
  tasks:
  - name: "Configure specific services"
    systemd:
      name: "{{ item.name }}"
      state: "{{ item.service_state }}"
      enabled: "{{ item.enabled }}"
    loop: "{{ daemon }}"
    